notification/urls.py
from __future__ import absolute_import, unicode_literals
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns("notification.views",
    url(r"^$", "notices", name="notification_notices"),
    url(r"^observe_toggle/(?P<content_type_id>\w+)/(?P<object_id>\w+)/(?P<signal>\w+)/(?P<notice_type_label>\w+)/$", "observe_toggle", name="notification_observe_toggle"),
    url(r"^observed_list/$", "observed_list", name="notification_observed_list"),
    url(r"^settings/$", "notice_settings", name="notification_notice_settings"),
    url(r"^(\d+)/$", "single", name="notification_notice"),
    url(r"^feed/$", "feed_for_user", name="notification_feed_for_user"),
    url(r"^mark_all_seen/$", "mark_all_seen", name="notification_mark_all_seen"),
    url(r'^unsubscribe/(.+)/$', "unsubscribe", name="notificaton_unsubscribe"),
)

notification/models.py
from __future__ import absolute_import, unicode_literals
import sys

try:
    import cPickle as pickle
except ImportError:
    import pickle

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.core.exceptions import ImproperlyConfigured, PermissionDenied
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.query import QuerySet, RawQuerySet
from django.template.loader import render_to_string
from django.utils.translation import ugettext_lazy as _
from django.utils import translation
from django.utils import timezone

from django.contrib.auth.models import User

from notification import backends
from notification.message import encode_message
from notification.managers import NoticeManager, ObservedItemManager, QueryDataManager
from notification.signals import should_deliver, delivered, configure
from notification.utils import permission_by_label

try:
    str = unicode  # Python 2.* compatible
    string_types = (basestring,)
    integer_types = (int, long)
except NameError:
    string_types = (str,)
    integer_types = (int,)

QUEUE_ALL = getattr(settings, "NOTIFICATION_QUEUE_ALL", False)


class LanguageStoreNotAvailable(Exception):
    pass


class NoticeType(models.Model):

    label = models.CharField(_("label"), max_length=40, unique=True)
    display = models.CharField(_("display"), max_length=50)
    description = models.CharField(_("description"), max_length=100)

    # by default only on for media with sensitivity less than or equal to this number
    default = models.IntegerField(_("default"))

    def __str__(self):
        return self.label

    class Meta:
        ordering = ("label", )
        verbose_name = _("notice type")
        verbose_name_plural = _("notice types")


NOTIFICATION_BACKENDS = backends.load_backends()

NOTICE_MEDIA = []
NOTICE_MEDIA_DEFAULTS = {}
for key, backend in list(NOTIFICATION_BACKENDS.items()):
    # key is a tuple (medium_id, backend_label)
    NOTICE_MEDIA.append(key)
    NOTICE_MEDIA_DEFAULTS[key[0]] = backend.spam_sensitivity


class NoticeSetting(models.Model):
    """
    Indicates, for a given user, whether to send notifications
    of a given type to a given medium.
    """

    user = models.ForeignKey(User, verbose_name=_("user"))
    notice_type = models.ForeignKey(NoticeType, verbose_name=_("notice type"))
    medium = models.CharField(_("medium"), max_length=1, choices=NOTICE_MEDIA)
    send = models.BooleanField(_("send"))

    class Meta:
        verbose_name = _("notice setting")
        verbose_name_plural = _("notice settings")
        unique_together = ("user", "notice_type", "medium")


def get_notification_setting(user, notice_type, medium):
    try:
        return NoticeSetting.objects.get(user=user, notice_type=notice_type, medium=medium)
    except NoticeSetting.DoesNotExist:
        default = (NOTICE_MEDIA_DEFAULTS[medium] <= notice_type.default)
        setting = NoticeSetting(user=user, notice_type=notice_type, medium=medium, send=default)
        setting.save()
        return setting


def should_send(user, notice_type, medium):
    return get_notification_setting(user, notice_type, medium).send


class NoticeUid(models.Model):
    """Prevents duplicates for same object by differents observed items"""
    recipient = models.ForeignKey(User, related_name="recieved_noticesuid", verbose_name=_("recipient"))
    notice_uid = models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return "{0} - {1}".format(self.recipient, self.notice_uid)

    class Meta:
        verbose_name = _("notice uid")
        verbose_name_plural = _("notice uids")
        unique_together = [('recipient', 'notice_uid', )]


class Notice(models.Model):

    recipient = models.ForeignKey(User, related_name="recieved_notices", verbose_name=_("recipient"))
    sender = models.ForeignKey(User, null=True, related_name="sent_notices", verbose_name=_("sender"))
    message = models.TextField(_("message"))
    notice_type = models.ForeignKey(NoticeType, verbose_name=_("notice type"))
    added = models.DateTimeField(_("added"), auto_now_add=True, db_index=True)
    unseen = models.BooleanField(_("unseen"), default=True, db_index=True)
    archived = models.BooleanField(_("archived"), default=False, db_index=True)
    on_site = models.BooleanField(_("on site"), db_index=True)

    objects = NoticeManager()

    def __str__(self):
        return self.message

    def archive(self):
        self.archived = True
        self.save()

    def is_unseen(self):
        """
        returns value of self.unseen but also changes it to false.

        Use this in a template to mark an unseen notice differently the first
        time it is shown.
        """
        unseen = self.unseen
        if unseen:
            self.unseen = False
            self.save()
        return unseen

    class Meta:
        ordering = ["-added"]
        verbose_name = _("notice")
        verbose_name_plural = _("notices")

    def get_absolute_url(self):
        return reverse("notification_notice", args=[str(self.pk)])


class NoticeQueueBatch(models.Model):
    """
    A queued notice.
    Denormalized data for a notice.
    """
    pickled_data = models.TextField()


def create_notice_type(label, display, description, default=2, verbosity=1):
    """
    Creates a new NoticeType.

    This is intended to be used by other apps as a post_syncdb manangement step.
    """
    try:
        notice_type = NoticeType.objects.get(label=label)
        updated = False
        if display != notice_type.display:
            notice_type.display = display
            updated = True
        if description != notice_type.description:
            notice_type.description = description
            updated = True
        if default != notice_type.default:
            notice_type.default = default
            updated = True
        if updated:
            notice_type.save()
            if verbosity > 1:
                print("Updated {0} NoticeType".format(label))
    except NoticeType.DoesNotExist:
        NoticeType(label=label, display=display, description=description, default=default).save()
        if verbosity > 1:
            print("Created {0} NoticeType".format(label))


def get_notification_language(user):
    """
    Returns site-specific notification language for this user. Raises
    LanguageStoreNotAvailable if this site does not use translated
    notifications.
    """
    if getattr(settings, "NOTIFICATION_LANGUAGE_MODULE", False):
        try:
            app_label, model_name = settings.NOTIFICATION_LANGUAGE_MODULE.split(".")
            model = models.get_model(app_label, model_name)
            language_model = model._default_manager.get(user__id__exact=user.id)
            if hasattr(language_model, "language"):
                return language_model.language
        except (ImportError, ImproperlyConfigured, model.DoesNotExist):
            raise LanguageStoreNotAvailable
    raise LanguageStoreNotAvailable


def get_formatted_messages(formats, label, context):
    """
    Returns a dictionary with the format identifier as the key. The values are
    are fully rendered templates with the given context.
    """
    format_templates = {}
    for format in formats:
        # conditionally turn off autoescaping for .txt extensions in format
        if format.endswith(".txt"):
            context.autoescape = False
        else:
            context.autoescape = True
        format_templates[format] = render_to_string((
            "notification/{0}/{1}".format(label, format),
            "notification/{0}".format(format)), context_instance=context)
    return format_templates


def send_now(users, label, extra_context=None, on_site=True, sender=None):
    """
    Creates a new notice.

    This is intended to be how other apps create new notices.

    notification.send(user, "friends_invite_sent", {
        "spam": "eggs",
        "foo": "bar",
    )

    You can pass in on_site=False to prevent the notice emitted from being
    displayed on the site.
    """
    sent = {}
    if extra_context is None:
        extra_context = {}

    notice_type = NoticeType.objects.get(label=label)
    notice_uid = extra_context.get('notice_uid', None)

    current_language = translation.get_language()
    current_timezone = timezone.get_current_timezone()

    for user in users:
        obj = extra_context.get('context_object',
                                extra_context.get('observed', None))
        if obj and not user.has_perm(permission_by_label(obj, 'view'), obj):
            continue

        if notice_uid:
            try:
                NoticeUid.objects.get(notice_uid=notice_uid, recipient=user)
                continue
            except NoticeUid.DoesNotExist:
                NoticeUid.objects.create(notice_uid=notice_uid, recipient=user)

        # Deprecated
        # get user language for user from language store defined in
        # NOTIFICATION_LANGUAGE_MODULE setting
        try:
            language = get_notification_language(user)
        except LanguageStoreNotAvailable:
            language = None

        # Deprecated
        result = {'pass': True}
        results = should_deliver.send(
            sender=Notice,
            result=result,
            recipient=user,
            label=label,
            notice_type=notice_type,
            extra_context=extra_context,
            sender_user=sender
        )
        if not result['pass']:
            continue
        if False in [i[1] for i in results]:
            continue

        results = configure.send(
            sender=Notice,
            recipient=user,
            label=label,
            notice_type=notice_type,
            extra_context=extra_context,
            sender_user=sender
        )
        configs = [i[1] for i in results if i[1]]

notification/templates/notification/base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block extra_head %}
    <link rel="alternate" type="application/atom+xml" title="Notices Feed" href="{% url notification_feed_for_user %}" />
    <link rel="stylesheet" href="{{ STATIC_URL }}pinax/css/notification.css" />
{% endblock %}

{% block body_class %}notices{% endblock %}

{% block subnav %}
    {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url notification_notices %}">{% trans "Notices" %}</a></li>
            <li><a href="{% url notification_notice_settings %}">{% trans "Notice settings" %}</a></li>
            <li><a href="{% url notification_observed_list %}">{% trans "Observed objects" %}</a></li>
        </ul>
    {% else %}
        &nbsp;
    {% endif %}
{% endblock %}

notification/templates/notification/email_body.html
{% spaceless %}
{% load i18n %}
{% endspaceless %}
<h1>{% blocktrans %}You have received the following notice from {{ current_site }}{% endblocktrans %}:</h1>

<div>{{ message }}</div>

<div>
--<br />
<a href="{{ notices_url }}">{% blocktrans %}Other notices{% endblocktrans %}</a> | 
<a href="{{ settings_url }}">{% blocktrans %}Notice settings{% endblocktrans %}</a> | 
<a href="{{ unsubscribe_url }}">{% blocktrans %}Unsubscribe for notice type "{{ notice }}"{% endblocktrans %}</a> | 
<a href="{{ unsubscribe_all_url }}">{% blocktrans %}Unsubscribe for all notices{% endblocktrans %}</a>
</div>

notification/templates/notification/full.html
{% load i18n %}{% blocktrans %}{{ notice }}{% endblocktrans %}

notification/templates/notification/notice.html
{% load i18n %}{% blocktrans %}{{ notice }}{% endblocktrans %}

notification/templates/notification/notice_settings.html
{% extends "notification/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Notification Settings" %}{% endblock %}

{% block body %}
    
    <div class="notice_settings">
        <h1>{% trans "Notification Settings" %}</h1>
        
        {% url acct_email as email_url %}
        {% if user.email %}
            <p>
                {% trans "Primary email" %}:<br />
                <b>{{ user.email }}</b><br />
                ({% blocktrans %}change under <a href="{{ email_url }}">Account</a>{% endblocktrans %})
            </p>
        {% else %}
            <p>
                <span class="warning">{% trans "Note" %}</span>:
                {% blocktrans %}You do not have a verified email address to which notices can be sent. You can add one by going to <a href="{{ email_url }}">Account</a>.{% endblocktrans %}
            </p>
        {% endif %}
        
        <form method="POST" action=""> {# doubt this easy to do in uni-form #}
            {% csrf_token %}
            <table class="notice_settings">
                <tr>
                    <th>{% trans "Notification Type" %}</th>
                    {% for header in notice_settings.column_headers %}
                        <th>{{ header }}</th>
                    {% endfor %}
                </tr>
                {% for row in notice_settings.rows %}
                    <tr>
                        <td>{% trans row.notice_type.display %}<br/>
                            <span class="notice_type_description">{% trans row.notice_type.description %}</span>
                        </td>
                        {% for cell in row.cells %}
                            <td>
                                <input type="checkbox" name="{{ cell.0 }}" {% if cell.1 %}checked="yes"{% endif %}/>
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
                <tr>
                    <td><input type="submit" value="{% trans "Change" %}" /></td>
                </tr>
            </table>
        </form>
    </div>
{% endblock %}

notification/templates/notification/notices.html
{% extends "notification/base.html" %}

{% load humanize %}
{% load i18n %}
{% load pagination_tags %}
{% load timezone_filters %}

{% block head_title %}{% trans "Notices" %}{% endblock %}

{% block body %}
    
    <h1>{% trans "Notices" %}</h1>
    
    {% autopaginate notices %}
    
    {% if notices %}
        <a href="{% url notification_mark_all_seen %}">{% trans "Mark all unseen notices seen" %}</a>
        
        {# TODO: get timezone support working with regroup #}
        {% regroup notices by added.date as notices_by_date %}
        
        {% for date in notices_by_date %}
            <h2 class="notice_date">{{ date.grouper|naturalday:_("MONTH_DAY_FORMAT")|capfirst }}</h2>
            
            {% for notice in date.list %}
                {% if notice.is_unseen %}
                    <div class="unseen_notice">
                {% else %}
                    <div class="notice">
                {% endif %}
                    <span class="notice_type">[{% trans notice.notice_type.display %}]</span>
                    <span class="notice_message">{{ notice.message|safe }}</span>
                    <span class="notice_time">{{ notice.added|localtime:account.timezone|time:"P" }}</span>
                </div>
            {% endfor %}
        {% endfor %}
        
        {% paginate %}
        
    {% else %}
        <p>{% trans "No notices." %}</p>
    {% endif %}
    
{% endblock %}

notification/templates/notification/observe_init.html
<script type="text/javascript">
    function notificationObserveToggle(url, el){
        jQuery.post(url, {csrfmiddlewaretoken: '{{ csrf_token }}'}, function(data) {
            if (data.success){
                var event = jQuery.Event('observeToggle');
                $(el).trigger(event, [data.observing]);
                if (!event.isDefaultPrevented()) {
                    if(data.observing){
                        $('span', el).first().css('display', 'none')
                        $('span', el).last().css('display', 'inline')
                    } else {
                        $('span', el).first().css('display', 'inline')
                        $('span', el).last().css('display', 'none')
                    }
                    $(el).trigger('observeToggled', [data.observing]);
                }
            }
        }, "json");
    }
    $(function(){
        $('.notification-observe-link').each(function(i, el){
            $(el).trigger('observeCreated', [$('span', el).last().is(":visible")]);
        });
    });
</script>

notification/templates/notification/observe_link.html
<a href="javascript:;" onclick="notificationObserveToggle('{% url notification_observe_toggle content_type_id=content_type_id, object_id=object_id, signal=signal, notice_type_label=notice_type %}', this); return false;" class="notification-observe-link"><span{% if observed %} style="display: none;"{% endif %}>{{ text_observe }}</span><span{% if not observed %} style="display: none;"{% endif %}>{{ text_stop_observing }}</span></a>

notification/templates/notification/observed_list.html
{% extends "notification/base.html" %}

{% load humanize %}
{% load i18n %}
{% load pagination_tags %}
{% load timezone_filters %}
{% load notification_observe_tags %}

{% block head_title %}{% trans "Observed objects" %}{% endblock %}

{% block extra_head %}
    {% include "notification/observe_init.html" %}
{% endblock %}

{% block body %}
    
    <h1>{% trans "Notices" %}</h1>
    
    {% autopaginate object_list %}
    
    {% if object_list %}
        
        {% for item in object_list %}
            {% ifchanged item.added|date:"Y-M-d" %}
                <h2 class="notice_date">{{ item.added|naturalday:_("DATE_FORMAT")|capfirst }}</h2>
            {% endifchanged %}
            <div class="notice">
            {% if item.observed_object %}
                <span class="notice-observed-object">
                    "<a href="{{ item.observed_object.get_absolute_url }}">{{ item.observed_object }}</a>"
                    [{% observe_link item.observed_object item.signal item.notice_type.label %}]
                </span>
                <span class="notice_type">[{% trans item.notice_type.display %}]</span>
                <span class="notice_time">{{ item.added|localtime:account.timezone|time:"P" }}</span>
            {% endif %}
            </div>
        {% endfor %}
        
        {% paginate %}
        
    {% else %}
        <p>{% trans "Not observed objects." %}</p>
    {% endif %}
    
{% endblock %}

notification/templates/notification/unsubscribed.html
{% extends "notification/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "You have been unsubscribed" %}{% endblock %}

{% block body %}
    <div>
        {% trans "You have been unsubscribed for next notifications" %}:

        {% if notice_settings %}
        <ul>
            {% for row in notice_settings %}
                <li>{% trans row.get_medium_display %}: {% trans row.notice_type.display %}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}